services:
  - type: web
    name: college-football-betting-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: college-football-db
          property: connectionString
      - key: THE_ODDS_API_KEY
        sync: false # Set manually in Render dashboard

databases:
  - name: college-football-db
    databaseName: college_football_betting
    plan: starter